### ISSUE TITLE
Plugin does not seem to work in terminator 1.91

### ISSUE THREAD

**Issue by Timple** [choffee/terminator-plugins#4]
The `searchplugin.py` file is still present in `~/.config/terminator/plugins/` but stopped working after upgrading to terminator 1.91.

The line failing is:
```python
        item = gtk.ImageMenuItem(gtk.STOCK_FIND)
```
The output in the bash windows (running terminator --debug):
```bash
TerminalPopupMenu::show: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
```

**Comment by Timple** [comment]
Never mind, it seemed to be an unrelated plugin interfering with the loading of this plugin

**Comment by MCFurry** [comment]
You still remember which plugin interfered? Got this same problem atm...
